#!/usr/bin/env bash
# make-example.sh — render templates/ with deterministic fake values into examples/.
# Output is committed; CI re-runs this and diff-checks for drift.

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

TEMPLATES="$REPO_ROOT/templates"
EXAMPLES="$REPO_ROOT/examples"

# Deterministic fake values — RFC 5737 docs IPs, all-zero UUID, sentinel keys.
# These are also in scripts/redact.sh ALLOWLIST_PLAINTEXT.
# These vars are consumed via indirect expansion (${!name}) in render().
# shellcheck disable=SC2034
declare_fakes_single() {
  UUID="00000000-0000-0000-0000-000000000000"
  REALITY_PRIVATE_KEY="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  REALITY_PUBLIC_KEY="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
  SHORT_ID=""
  SUB_TOKEN="example-token-do-not-use"
  SERVER_IP="203.0.113.10"
  SNI="addons.mozilla.org"
  INBOUND_PORT="443"
  NODE_NAME="Example-Resi-01"
}

# shellcheck disable=SC2034
declare_fakes_dual() {
  RESI_UUID="00000000-0000-0000-0000-000000000000"
  RESI_REALITY_PRIVATE_KEY="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  RESI_REALITY_PUBLIC_KEY="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
  RESI_SHORT_ID=""
  RESI_SERVER_IP="203.0.113.10"
  RESI_SNI="addons.mozilla.org"
  RESI_INBOUND_PORT="443"
  RESI_NODE_NAME="Example-Resi-01"

  DC_UUID="11111111-1111-1111-1111-111111111111"
  DC_REALITY_PRIVATE_KEY="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  DC_REALITY_PUBLIC_KEY="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
  DC_SHORT_ID=""
  DC_SERVER_IP="198.51.100.20"
  DC_SNI="addons.mozilla.org"
  DC_INBOUND_PORT="443"
  DC_NODE_NAME="Example-DC-01"
}

# render <template-file> <output-file>
# Replaces every @@VAR@@ token in template with $VAR from the environment.
# Uses awk for portable, safe substitution (no eval, no envsubst footguns).
render() {
  local in="$1" out="$2"
  mkdir -p "$(dirname "$out")"
  # Collect all @@VAR@@ tokens from the template.
  local vars
  vars="$(grep -oE '@@[A-Z_]+@@' "$in" 2>/dev/null | sort -u || true)"

  local tmp
  tmp="$(mktemp)"
  cp "$in" "$tmp"

  local token name value
  while IFS= read -r token; do
    [[ -z "$token" ]] && continue
    name="${token//@/}"
    value="${!name-}"
    if [[ -z "${!name+x}" ]]; then
      echo "render: missing variable for $token in $in" >&2
      rm -f "$tmp"
      exit 1
    fi
    # Use perl-style sed avoid: just use awk for clarity.
    python3 - "$tmp" "$token" "$value" <<'PY'
import sys, pathlib
path, token, value = sys.argv[1], sys.argv[2], sys.argv[3]
p = pathlib.Path(path)
p.write_text(p.read_text().replace(token, value))
PY
  done <<<"$vars"

  mv "$tmp" "$out"
}

main() {
  rm -rf "$EXAMPLES/single-node" "$EXAMPLES/dual-node"
  mkdir -p "$EXAMPLES/single-node" "$EXAMPLES/dual-node"

  # ── Single-node example ────────────────────────────────────────────
  declare_fakes_single

  render "$TEMPLATES/singbox/11_xtls-reality_inbounds.json.tmpl" \
    "$EXAMPLES/single-node/11_xtls-reality_inbounds.json"
  cp "$TEMPLATES/singbox/00_log.json" "$EXAMPLES/single-node/00_log.json"
  cp "$TEMPLATES/singbox/01_outbounds.json" "$EXAMPLES/single-node/01_outbounds.json"
  cp "$TEMPLATES/singbox/03_route.json" "$EXAMPLES/single-node/03_route.json"
  cp "$TEMPLATES/singbox/05_dns.json" "$EXAMPLES/single-node/05_dns.json"
  cp "$TEMPLATES/singbox/06_ntp.json" "$EXAMPLES/single-node/06_ntp.json"

  render "$TEMPLATES/clash/client-single.yaml.tmpl" \
    "$EXAMPLES/single-node/clash-profile.yaml"

  render "$TEMPLATES/singbox-client/outbound.json.tmpl" \
    "$EXAMPLES/single-node/sing-box-client-outbound.json"

  # vless:// link
  cat >"$EXAMPLES/single-node/vless-link.txt" <<EOF
vless://${UUID}@${SERVER_IP}:${INBOUND_PORT}?encryption=none&flow=xtls-rprx-vision&security=reality&sni=${SNI}&fp=chrome&pbk=${REALITY_PUBLIC_KEY}&sid=${SHORT_ID}&type=tcp#${NODE_NAME}
EOF

  # ── Dual-node example ──────────────────────────────────────────────
  declare_fakes_dual

  render "$TEMPLATES/clash/client-dual.yaml.tmpl" \
    "$EXAMPLES/dual-node/clash-profile.yaml"

  cat >"$EXAMPLES/dual-node/vless-links.txt" <<EOF
vless://${RESI_UUID}@${RESI_SERVER_IP}:${RESI_INBOUND_PORT}?encryption=none&flow=xtls-rprx-vision&security=reality&sni=${RESI_SNI}&fp=chrome&pbk=${RESI_REALITY_PUBLIC_KEY}&sid=${RESI_SHORT_ID}&type=tcp#${RESI_NODE_NAME}
vless://${DC_UUID}@${DC_SERVER_IP}:${DC_INBOUND_PORT}?encryption=none&flow=xtls-rprx-vision&security=reality&sni=${DC_SNI}&fp=chrome&pbk=${DC_REALITY_PUBLIC_KEY}&sid=${DC_SHORT_ID}&type=tcp#${DC_NODE_NAME}
EOF

  # ── Example READMEs ────────────────────────────────────────────────
  cat >"$EXAMPLES/README.md" <<'EOF'
# examples/

Auto-generated by `scripts/make-example.sh` from `templates/`.

**All values are placeholders.** Specifically:
- UUIDs are all-zero / all-ones sentinels
- IPs are RFC 5737 documentation ranges (`203.0.113.0/24`, `198.51.100.0/24`)
- Reality public/private keys are sentinel `AAA…` / `BBB…` strings (NOT valid Curve25519 keys — these will not work as live credentials)
- Subscription token is the literal string `example-token-do-not-use`

Do not deploy these. Use `install/install.sh` to generate real values for your VPS.

## Contents

- `single-node/` — Minimum viable VLESS+Reality on one VPS.
- `dual-node/`   — Residential leaf + data-center aggregator, with smart Clash routing that splits Telegram / Discord (data-center) from OpenAI / Anthropic / Netflix (residential).
EOF

  echo "examples/ regenerated."
}

main "$@"
